const base = process.env.TRAINING_SMOKE_URL || 'https://easy-express-sites-izwi.vercel.app';
let cookie = '';
async function request(action, input = {}, expected = 200, headers = {}) {
  const r = await fetch(base + '/api/training', { method: 'POST', headers: { 'Content-Type':'application/json', ...(cookie ? { Cookie: cookie } : {}), ...headers }, body: JSON.stringify({ action, ...input }) });
  const p = await r.json().catch(()=>({}));
  if (r.status !== expected) throw new Error(`${action}: expected ${expected}, received ${r.status}: ${p.error || 'unknown error'}`);
  const set = r.headers.get('set-cookie'); if(set)cookie=set.split(';')[0]; return p.data || p;
}
await request('snapshot', { employeeId:'CA613F3FEACEFDC6', role:'ceo' }, 401);
await request('demo', {}, 403, { Origin:'https://unauthorized.example.invalid' });
let d = await request('demo');
await request('gameAccess', {}, 403);
await request('gameplayEvents', {events:[]},403);
await request('installer', {},503);
if(!d.demo || d.me.role!=='ceo' || d.employees.length!==4 || d.gameLevels.length!==10 || d.gameEvents.length!==12)throw new Error('Game demonstration isolation failed');
if(d.gameEvents.filter(e=>e.type==='job_submitted'&&e.jobType==='build'&&e.outcome==='success').length!==2 || d.gameEvents.filter(e=>e.type==='job_submitted'&&e.outcome==='failed').length!==1)throw new Error('Game outcome definitions failed');
const accessRequest=d.accessRequests.find(r=>r.status==='pending');
if(!accessRequest)throw new Error('Missing fictional access request');
await request('reviewAccessRequest',{requestId:accessRequest.id,decision:'approved',group:'QA onboarding'});
d=await request('snapshot');
if(!d.employees.some(e=>e.id===accessRequest.playerId&&e.active&&e.group==='QA onboarding') || d.accessRequests.find(r=>r.id===accessRequest.id)?.status!=='approved')throw new Error('Approval persistence failed');
const employee = await request('provision',{ name:'Production smoke fixture', email:'qa@example.invalid', group:'EasyPC' });
await request('setRole',{id:employee.id,role:'admin'});
d=await request('snapshot');
if(!d.employees.some(e=>e.id===employee.id&&e.role==='admin'&&e.group==='EasyPC') || d.gameSessions.length!==3)throw new Error('Persisted workplace/role or game sessions missing');
await request('demoRole',{role:'employee'});
d=await request('snapshot');
if(d.employees.length!==1 || d.gameEvents.length!==4 || d.gameEvents.some(a=>a.employeeId!=='DEMO001') || d.gameSessions.some(s=>s.employeeId!=='DEMO001'))throw new Error('Employee gameplay scope failed');
await request('setRole',{id:employee.id,role:'admin'},403);
await request('reviewAccessRequest',{requestId:accessRequest.id,decision:'approved',group:'IT'},403);
await request('gameplayHeartbeat',{sessionId:d.gameSessions[0].id},403);
await request('logout'); await request('snapshot',{},401);
console.log('PASS: production anonymous/cross-origin denial, ten game levels, fictional game outcomes, durable workplace and CEO role grants, employee gameplay scoping, role denial, demo game/download/reporting denial and logout. Real PlayFab sign-in and a Unity level playthrough are separate checks.');
