export const DLC_CATALOG = [
  {
    packId: "dlc_neon_diagnostics",
    entitlement: "DLC_NEON_DIAGNOSTICS",
    name: "Neon Diagnostics Pack",
    price: "₱169",
    accent: "#55d7f5",
    tag: "Technical lab",
    description: "Turn the repair bay into a sharper, more professional diagnostics workspace.",
    benefit: "Four balanced ambience bonuses (0.45–0.75 each) through the existing furniture reputation cap.",
    image: "/gallery/Diagnose.png",
    items: ["Neon Diagnostic Wall Panel", "Circuit Diagnostics Wall Display", "Multi-Monitor Repair Display", "Technician Status Terminal"],
  },
  {
    packId: "dlc_customer_lounge",
    entitlement: "DLC_CUSTOMER_LOUNGE",
    name: "Customer Lounge Pack",
    price: "₱199",
    accent: "#54df9d",
    tag: "Comfort & trust",
    description: "Create a welcoming waiting area that makes every customer feel looked after.",
    benefit: "Four modest ambience bonuses (0.45–1.00 each) through the existing furniture reputation cap.",
    image: "/gallery/Shopinterior.png",
    items: ["Premium Waiting Couch", "Guest Refreshment Shelf", "Indoor Plant Arrangement", "Customer Information Display"],
  },
  {
    packId: "dlc_showroom_pro",
    entitlement: "DLC_SHOWROOM_PRO",
    name: "Showroom Pro Pack",
    price: "₱229",
    accent: "#ffb24c",
    tag: "Premium presentation",
    description: "Give components and finished builds a polished retail showroom presentation.",
    benefit: "Four modest ambience bonuses (0.60–1.00 each) through the existing furniture reputation cap.",
    image: "/gallery/hero-workshop-v2.jpg",
    items: ["Glass Hardware Display Cabinet", "Premium Component Retail Shelf", "Curved Showcase Monitor", "Showroom Brand Wall"],
  },
];
