export const DLC_CATALOG = [
  {
    packId: "dlc_neon_diagnostics",
    entitlement: "DLC_NEON_DIAGNOSTICS",
    name: "Neon Diagnostics Pack",
    price: "₱169",
    accent: "#55d7f5",
    tag: "Technical lab",
    description: "Show clear repair diagnostics, organized check-in, real queue status, and the components behind each repair.",
    benefit: "Four optional ambience bonuses (0.60–0.80 each; +2.75 total) within the furniture reputation cap.",
    image: "/gallery/dlc-neon-diagnostics.png",
    items: ["Holographic Diagnostic Wall", "Suspended Motherboard Display", "Technician Check-In Kiosk", "Live Customer Queue Display"],
  },
  {
    packId: "dlc_showroom_pro",
    entitlement: "DLC_SHOWROOM_PRO",
    name: "Showroom Pro Pack",
    price: "₱229",
    accent: "#ffb24c",
    tag: "Premium presentation",
    description: "Present completed PC builds with a dedicated podium, glass tower, Easy Express sign, and floor wayfinding.",
    benefit: "Four optional ambience bonuses (0.45–0.90 each; +2.95 total) within the furniture reputation cap.",
    image: "/gallery/dlc-showroom-pro.png",
    items: ["Premium PC Showcase Podium", "Transparent PC Showcase Tower", "Easy Express Neon Sign", "RGB Cable-Light Floor System"],
  },
  {
    packId: "dlc_customer_lounge",
    entitlement: "DLC_CUSTOMER_LOUNGE",
    name: "Customer Lounge Pack",
    price: "₱199",
    accent: "#54df9d",
    tag: "Comfort & trust",
    description: "Give guests a comfortable place to wait, a simple refreshment station, greenery, and a clear guide to the repair process.",
    benefit: "Four optional ambience bonuses (0.50–0.80 each; +2.45 total) within the furniture reputation cap.",
    image: "/gallery/dlc-customer-lounge.png",
    items: ["Premium Waiting Couch", "Guest Refreshment Shelf", "Indoor Plant Arrangement", "Customer Information Display"],
  },
];
