import { useEffect, useState } from 'react';
import './training.css';

async function api(action, input = {}) {
  const r = await fetch('/api/training', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...input }) });
  const p = await r.json().catch(() => ({}));
  if (!r.ok) throw Object.assign(new Error(p.error || 'The service is unavailable. Please try again.'), { status: r.status });
  return p.data || p;
}
const formatDate = d => d ? new Date(d.length === 10 ? d + 'T12:00:00' : d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : 'Not recorded';
const formatTime = d => d ? new Date(d).toLocaleString('en-US') : 'Not recorded';
const label = s => (s || 'not started').replaceAll('_', ' ');
const initials = n => n.split(' ').map(s => s[0]).slice(0, 2).join('');
function Icon({ name, ...props }) {
  const paths = { dashboard: 'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z', training: 'M4 4h16v16H4z M8 8h8 M8 12h8 M8 16h5', performance: 'M4 20V4 M4 20h17 M8 16v-4 M13 16V8 M18 16V5', employees: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 3a4 4 0 1 0 0 8a4 4 0 0 0 0-8 M20 8v6 M17 11h6', sessions: 'M3 4h18v13H3z M8 21h8 M12 17v4 M7 11h3l2-4 2 6 2-2h2', resources: 'M3 5c4-2 7-2 9 0c2-2 5-2 9 0v15c-4-2-7-2-9 0c-2-2-5-2-9 0z M12 5v15', arrow: 'M5 12h14 M14 7l5 5-5 5', check: 'M5 12l4 4L19 6', settings: 'M12 3v3 M12 18v3 M3 12h3 M18 12h3 M6 6l2 2 M16 16l2 2 M6 18l2-2 M16 8l2-2 M12 8a4 4 0 1 0 0 8a4 4 0 0 0 0-8' };
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}><path d={paths[name] || paths.training} /></svg>;
}
function Brand() { return <a className="ee-brand" href="#/" aria-label="Easy Express home"><span className="ee-mark">E<span>E</span></span><span><strong>Easy Express</strong><small>TRAINING PORTAL</small></span></a>; }
function Badge({ status }) { return <span className={'badge badge-' + status}>{label(status)}</span>; }
function Empty({ title = 'No records yet', children }) { return <div className="empty"><Icon name="training" width="32" height="32" /><h3>{title}</h3><p>{children || 'Records will appear here when training activity is received.'}</p></div>; }
function Modal({ title, onClose, children }) {
  useEffect(() => {
    const previous = document.activeElement;
    const close = e => { if (e.key === 'Escape') onClose(); if (e.key === 'Tab') { const nodes = [...document.querySelectorAll('.modal button, .modal input, .modal select, .modal textarea, .modal a')].filter(n => !n.disabled); if (e.shiftKey && document.activeElement === nodes[0]) { e.preventDefault(); nodes.at(-1)?.focus(); } else if (!e.shiftKey && document.activeElement === nodes.at(-1)) { e.preventDefault(); nodes[0]?.focus(); } } };
    document.querySelector('.modal button')?.focus(); document.addEventListener('keydown', close);
    return () => { document.removeEventListener('keydown', close); previous?.focus(); };
  }, [onClose]);
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog">×</button></header>{children}</section></div>;
}
function assignmentStatus(a, attempts) {
  const all = attempts.filter(t => t.assignmentId === a.id);
  if (all.some(t => t.result === 'passed')) return 'passed';
  if (all.some(t => t.state === 'in_progress')) return 'in_progress';
  if (all.some(t => t.result === 'needs_another_attempt')) return 'needs_another_attempt';
  if (all.some(t => t.state === 'submitted')) return 'submitted';
  return 'not_started';
}
function PublicPage({ busy, onLogin, onDemo, error }) {
  return <div className="public"><header className="public-header"><Brand /><nav><a href="#purpose">Training approach</a><a href="#workflow">How it works</a><button className="btn" onClick={onLogin}>Employee sign in <Icon name="arrow" /></button></nav></header>
    <main><section className="public-hero"><div><span className="eyebrow">THE PC WORKSHOP. A PLACE TO LEARN.</span><h1>Build confidence.<br /><em>One component<br />at a time.</em></h1><p>Practice PC hardware fundamentals in Easy Express, then turn each training attempt into clear progress and useful feedback.</p><div className="actions"><button className="btn" onClick={onLogin}>Sign in to your workspace <Icon name="arrow" /></button><button className="btn secondary" disabled={busy} onClick={onDemo}>{busy ? 'Opening…' : 'Explore thesis demonstration'}</button></div><small>Employee access is provisioned by your training administrator.</small>{error && <div role="alert" className="alert error">{error}</div>}</div><div className="hero-image"><img src="/gallery/Shopinterior.png" alt="The PC workshop inside Easy Express" /><div className="image-caption"><span className="live-dot" /><div><strong>Your workshop, your learning environment</strong><small>Easy Express · Unity PC simulation</small></div></div></div></section>
      <section id="purpose" className="public-purpose"><div><span className="eyebrow">PURPOSEFUL PRACTICE</span><h2>A simulation with a<br />training workflow behind it.</h2></div><p>The Unity game is where employees learn by doing. The portal connects assigned training, recorded knowledge checks, attempt review and administrator feedback in one workspace.</p></section><section className="capabilities">{[['01','Learn the hardware','Identify components and develop safe handling habits.'],['02','Practice in the workshop','Follow the existing game’s PC component tutorial.'],['03','Review the evidence','Understand first-try answers and compare compatible attempts.']].map(([n,t,p]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</section>
      <section id="workflow" className="public-workflow"><img src="/gallery/Diagnose.png" alt="Component inspection inside Easy Express" /><div><span className="eyebrow">FROM ASSIGNMENT TO FEEDBACK</span><h2>A clear next step<br />at every stage.</h2><ol><li>Your administrator provisions access and assigns training.</li><li>You sign into the approved Easy Express build and complete a check.</li><li>Recorded results reach your employee workspace.</li><li>Your administrator reviews your attempt and provides feedback.</li></ol><p className="muted">The demonstration uses fictional employees and sample sessions. It does not show real employee performance.</p></div></section></main><footer><Brand /><span>Employee training & assessment · Easy Express</span><a href="#/login">Authorized access</a></footer></div>;
}
function Login({ onSubmit, onBack, busy, error }) {
  const [recover, setRecover] = useState(false), [message, setMessage] = useState('');
  return <div className="login-page"><aside><Brand /><div><span className="eyebrow">WELCOME TO YOUR WORKSHOP</span><h1>Practice.<br />Learn.<br /><em>Progress.</em></h1><p>Your existing Easy Express game account connects your training and feedback.</p></div><small>Access is managed by your company’s training team.</small></aside><main><button className="text-button" onClick={onBack}>← Back to training portal</button><form onSubmit={async e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); if (recover) { try { const r = await api('recover', f); setMessage(r.message); } catch (e) { setMessage(e.message); } } else onSubmit(f); }}><span className="eyebrow">AUTHORIZED EMPLOYEES</span><h2>{recover ? 'Account recovery' : 'Sign in to Easy Express'}</h2><p>{recover ? 'Use the email registered with your game account.' : 'Use the same email and password you use in the game.'}</p>{error && <div className="alert error" role="alert">{error}</div>}{message && <div className="alert" role="status">{message}</div>}<label>Email address<input name="email" type="email" autoComplete="username" required /></label>{!recover && <label>Password<input name="password" type="password" autoComplete="current-password" required /></label>}<button className="btn" disabled={busy}>{busy ? 'Checking access…' : recover ? 'Send recovery instructions' : 'Sign in'}<Icon name="arrow" /></button><button type="button" className="text-button" onClick={() => { setRecover(!recover); setMessage(''); }}>{recover ? 'Return to sign in' : 'Forgot your password?'}</button><div className="login-note">Need access? Contact your training administrator. Accounts must be authorized before using the portal or training build.</div></form></main></div>;
}
function ProvisionForm({ data, groups, busy, onSave }) {
  const [createAccount, setCreateAccount] = useState(false);
  return <form onSubmit={e => { e.preventDefault(); onSave({...Object.fromEntries(new FormData(e.currentTarget)),createAccount}); }}>
    <div className="alert">Employee access uses the same PlayFab identity in the portal and Unity game.</div>
    {!data.demo && <label>Account onboarding<select value={createAccount?'new':'existing'} onChange={e=>setCreateAccount(e.target.value==='new')}><option value="existing">Link an existing game account</option><option value="new">Create a new employee game account</option></select></label>}
    {!createAccount && <label>PlayFab ID<input name="id" required={!data.demo} maxLength="100" placeholder={data.demo?'Generated fictional ID':'Existing game player ID'}/></label>}
    <label>Employee name<input name="name" required maxLength="200"/></label><label>Registered game email<input name="email" type="email" required/></label>
    {createAccount && <><label>Game username<input name="username" required minLength="3" maxLength="20" pattern="[A-Za-z0-9]+" autoComplete="off"/></label><label>Initial password<input name="password" type="password" required minLength="8" autoComplete="new-password"/></label><p className="muted small">Share the initial credentials through your company’s approved channel. The portal does not store or email the password. The employee can use account recovery to change it.</p></>}
    <label>Department / training group<input name="group" required list="groups"/><datalist id="groups">{groups.map(g=><option value={g} key={g}/>)}</datalist></label><button className="btn" disabled={busy}>Provision employee access</button>
  </form>;
}
function Stat({ title, value, note, accent }) { return <article className={'stat ' + (accent ? 'stat-accent' : '')}><span>{title}</span><strong>{value}</strong><small>{note}</small></article>; }
function AssignmentTable({ data, onOpen, admin }) {
  if (!data.assignments.length) return <Empty title="No training assigned">Your training administrator can assign the supported component fundamentals scenario.</Empty>;
  return <div className="table-wrap"><table><thead><tr><th>Training scenario</th>{admin && <th>Employee</th>}<th>Due date</th><th>Status</th><th>Attempts</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{data.assignments.map(a => <tr key={a.id}><td><strong>{a.title}</strong><small>Foundation · Rubric {a.rubric.passPercent}% pass</small></td>{admin && <td>{data.employees.find(e => e.id === a.employeeId)?.name || a.employeeId}</td>}<td>{formatDate(a.dueDate)}{a.dueDate < new Date().toISOString().slice(0,10) && assignmentStatus(a,data.attempts) !== 'passed' && <small className="danger">Overdue</small>}</td><td><Badge status={assignmentStatus(a,data.attempts)} /></td><td>{data.attempts.filter(t => t.assignmentId === a.id).length} / {a.attemptLimit}</td><td><button className="text-button" onClick={() => onOpen(a)}>View <Icon name="arrow" width="15" /></button></td></tr>)}</tbody></table></div>;
}
function AttemptReview({ attempt, data, onFeedback, busy }) {
  const employee = data.employees.find(e => e.id === attempt.employeeId);
  const comparable = data.attempts.filter(a => a.employeeId === attempt.employeeId && a.scenarioVersion === attempt.scenarioVersion && a.rubric.version === attempt.rubric.version && a.phase === attempt.phase && a.score != null);
  return <><p className="muted">{employee?.name} · {attempt.mode === 'practice' ? 'Free practice' : 'Assigned assessment'} · {formatTime(attempt.startedAt)}</p><div className="review-stats"><Stat title="Knowledge accuracy" value={attempt.score == null ? '—' : attempt.score + '%'} note={attempt.score == null ? 'Not recorded' : `${attempt.correct} / 10 first-try answers`} /><Stat title="Tutorial time" value={attempt.tutorialSeconds == null ? '—' : Math.round(attempt.tutorialSeconds / 60) + ' min'} note="Includes tutorial UI time" /><Stat title="Result" value={label(attempt.result || attempt.state)} note={`Pass mark: ${attempt.rubric.passPercent}%`} /></div><p className="muted small">Build: {attempt.build} · Scenario v{attempt.scenarioVersion} · Rubric: {attempt.rubric.version} · Phase: {attempt.phase || 'Not recorded'}</p><h3>Recorded event timeline</h3><p className="muted">These are received game events. This is not a video replay.</p><ol className="timeline">{attempt.events.map(e => <li key={e.id}><span className={e.correct === false ? 'timeline-dot wrong' : 'timeline-dot'} /><div><strong>{e.type === 'answer' ? `${e.skill} · ${e.correct ? 'Correct' : 'Incorrect'} first answer` : label(e.type)}</strong><p>{e.questionId || label(e.result)}{e.phase ? ' · ' + e.phase : ''}</p><small title={'Received: ' + formatTime(e.receivedAt)}>{formatTime(e.timestamp)}</small></div></li>)}</ol>{!attempt.events.length && <Empty title="Awaiting game events" />}
    <h3>Comparable attempt history</h3><div className="comparison">{comparable.map((a,i) => <div key={a.id}><span>Attempt {i+1}</span><div><i style={{ width: a.score + '%' }} /></div><strong>{a.score}%</strong></div>)}</div><p className="muted small">Same employee, scenario version, rubric version and check phase. Sample size: {comparable.length}.</p><div className="unrecorded"><strong>Not recorded</strong><span>Hints · Assembly errors · Procedure mistakes · Active task time</span></div><h3>Administrator feedback</h3>{attempt.feedback.length ? attempt.feedback.map(f => <blockquote key={f.id}>{f.text}<cite>{data.employees.find(e => e.id === f.author)?.name || 'Administrator'} · {formatTime(f.at)}</cite></blockquote>) : <p className="muted">No feedback has been added to this attempt.</p>}{data.me.role !== 'employee' && attempt.state === 'submitted' && <form onSubmit={e => { e.preventDefault(); onFeedback(new FormData(e.currentTarget).get('text')); }}><label>Add feedback for this attempt<textarea name="text" maxLength="2000" required rows="3" /></label><button className="btn" disabled={busy}>Save feedback</button></form>}</>;
}
function Dashboard({ data, navigate, openAttempt, openAssignment, admin }) {
  const assessed = data.attempts.filter(a => a.mode === 'assessment' && a.score != null);
  const completed = data.assignments.filter(a => data.attempts.some(t => t.assignmentId === a.id && t.state === 'submitted' && t.result !== 'abandoned')).length;
  const passed = assessed.filter(a => a.result === 'passed').length;
  const overdue = data.assignments.filter(a => a.dueDate < new Date().toISOString().slice(0,10) && assignmentStatus(a,data.attempts) !== 'passed').length;
  const next = data.assignments.find(a => assignmentStatus(a,data.attempts) !== 'passed');
  const mistakes = [...new Set(data.attempts.flatMap(a => a.events.filter(e => e.type === 'answer' && !e.correct).map(e => e.skill)))];
  return <><div className="page-title"><div><span className="eyebrow">{admin ? 'TRAINING AT A GLANCE' : 'YOUR LEARNING WORKSPACE'}</span><h1>{admin ? 'Training overview' : `Welcome back, ${data.me.name.split(' ')[0]}.`}</h1><p>{admin ? 'Follow assignments, review evidence and support each employee’s progress.' : 'A little practice today. More confidence in the workshop tomorrow.'}</p></div><span className="date-chip">{formatDate(new Date().toISOString())}</span></div>
    <div className="stats"><Stat title="Assigned training" value={data.assignments.length} note={`${data.assignments.filter(a => assignmentStatus(a,data.attempts)==='in_progress').length} in progress · ${overdue} overdue`} /><Stat title="Completion rate" value={data.assignments.length ? Math.round(completed/data.assignments.length*100)+'%' : '—'} note={`${completed} / ${data.assignments.length} assignments submitted`} accent /><Stat title="Assessment pass rate" value={assessed.length ? Math.round(passed/assessed.length*100)+'%' : '—'} note={`${passed} / ${assessed.length} scored assessment attempts`} /><Stat title={admin ? 'Need additional practice' : 'Practice priorities'} value={admin ? new Set(assessed.filter(a=>a.result==='needs_another_attempt').map(a=>a.employeeId)).size : mistakes.length} note={admin ? 'Employees with an unsuccessful attempt' : 'Skills with an incorrect first answer'} /></div>
    <div className="dashboard-grid"><section className="next-card"><div><span className="eyebrow">{admin ? 'GUIDE THE NEXT STEP' : 'YOUR NEXT STEP'}</span><h2>{admin ? 'Good training starts with a clear assignment.' : next ? next.title : 'You’re ready for your next assignment.'}</h2><p>{admin ? 'Assign the supported game scenario to an employee or training group, with a due date and a versioned pass mark.' : next ? `Due ${formatDate(next.dueDate)}. Review the learning objectives and use the approved training build.` : 'Review your results or contact your training administrator for your next task.'}</p><button className="btn" onClick={()=> admin ? navigate('training') : next ? openAssignment(next) : navigate('performance')}>{admin ? 'Manage training' : next ? 'Review assignment' : 'Review performance'}<Icon name="arrow" /></button></div><img src="/gallery/Diagnose.png" alt="PC component inspection in Easy Express" /></section><section className="panel priorities"><span className="eyebrow">FOCUS AREAS</span><h2>{admin ? 'Support another attempt' : 'Skills to revisit'}</h2>{mistakes.length ? mistakes.slice(0,4).map(m => <div className="priority-row" key={m}><Icon name="training" /><span>{m}</span></div>) : <p className="muted">Focus areas appear after recorded knowledge checks.</p>}<button className="text-button" onClick={()=>navigate('performance')}>View recorded answers <Icon name="arrow" /></button></section></div>
    <section className="panel"><div className="section-heading"><div><span className="eyebrow">{admin ? 'ASSIGNMENT TRACKER' : 'MY TRAINING'}</span><h2>{admin ? 'Training assignments' : 'Keep your training moving'}</h2></div><button className="text-button" onClick={()=>navigate('training')}>View all <Icon name="arrow" /></button></div><AssignmentTable data={{...data,assignments:data.assignments.slice(0,4)}} admin={admin} onOpen={openAssignment} /></section><div className="dashboard-grid equal"><section className="panel"><div className="section-heading"><h2>Recent results</h2><button className="text-button" onClick={()=>navigate('performance')}>All attempts</button></div>{data.attempts.length ? data.attempts.slice(-4).reverse().map(a => <button className="result-row" key={a.id} onClick={()=>openAttempt(a)}><span className="score-disc">{a.score==null ? '—' : a.score+'%'}</span><span><strong>{data.scenario.title}</strong><small>{admin ? (data.employees.find(e=>e.id===a.employeeId)?.name)+' · ' : ''}{formatDate(a.startedAt)} · {a.mode}</small></span><Badge status={a.result || a.state} /></button>) : <Empty title="No attempts yet" />}</section><section className="panel"><h2>Latest feedback</h2>{data.attempts.flatMap(a=>a.feedback.map(f=>({...f,attempt:a}))).slice(-3).reverse().map(f=><button key={f.id} className="feedback-row" onClick={()=>openAttempt(f.attempt)}><span className="eyebrow">{formatDate(f.at)}</span><p>{f.text}</p><small>Open assessment <Icon name="arrow" width="14" /></small></button>)}{!data.attempts.some(a=>a.feedback.length) && <Empty title="Feedback will appear here">Your administrator’s comments stay linked to the correct attempt.</Empty>}</section></div></>;
}
function Performance({ data, openAttempt }) {
  const [query,setQuery]=useState(''),[group,setGroup]=useState(''),[result,setResult]=useState(''),[mode,setMode]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
  const groups=[...new Set(data.employees.map(e=>e.group))];
  const rows=data.attempts.filter(a=>{ const e=data.employees.find(e=>e.id===a.employeeId); return (!query || (e?.name+' '+a.employeeId).toLowerCase().includes(query.toLowerCase())) && (!group || e?.group===group) && (!result || a.result===result) && (!mode || a.mode===mode) && (!from || a.startedAt.slice(0,10)>=from) && (!to || a.startedAt.slice(0,10)<=to); });
  const exportCsv=()=>{ const cell=v=>'"'+String(v??'Not recorded').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"'; const header=['employee_id','employee','group','attempt_id','assignment_id','scenario','scenario_version','rubric_version','mode','started_at','result','score_percent','tutorial_seconds','feedback']; const lines=rows.map(a=>{const e=data.employees.find(e=>e.id===a.employeeId);return [a.employeeId,e?.name,e?.group,a.id,a.assignmentId,a.scenarioId,a.scenarioVersion,a.rubric.version,a.mode,a.startedAt,a.result,a.score,a.tutorialSeconds,a.feedback.map(f=>f.text).join(' | ')].map(cell).join(',');}); const url=URL.createObjectURL(new Blob(['\uFEFF'+header.join(',')+'\r\n'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'})); const anchor=document.createElement('a');anchor.href=url;anchor.download='easy-express-filtered-results.csv';anchor.click();URL.revokeObjectURL(url); };
  return <><div className="page-title"><div><span className="eyebrow">RECORDED TRAINING EVIDENCE</span><h1>{data.me.role==='employee' ? 'My performance' : 'Performance review'}</h1><p>Review actual first answers, assessment results and attempt-specific feedback.</p></div><button className="btn secondary" onClick={exportCsv}>Export filtered CSV</button></div><section className="panel"><div className="filters"><label>Employee search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or player ID" /></label>{data.me.role!=='employee' && <label>Department / group<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">All groups</option>{groups.map(g=><option key={g}>{g}</option>)}</select></label>}<label>Result<select value={result} onChange={e=>setResult(e.target.value)}><option value="">All results</option><option value="passed">Passed</option><option value="needs_another_attempt">Needs another attempt</option><option value="abandoned">Abandoned</option></select></label><label>Session type<select value={mode} onChange={e=>setMode(e.target.value)}><option value="">All types</option><option value="assessment">Assessment</option><option value="practice">Practice</option></select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} /></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)} /></label></div><p className="muted small">Scenario: PC component fundamentals · {rows.length} matching attempts. Exports contain these filtered records.</p>{rows.length ? <div className="table-wrap"><table><thead><tr><th>Employee / assessment</th><th>Date</th><th>Type</th><th>Accuracy</th><th>Result</th><th>Review</th></tr></thead><tbody>{rows.slice().reverse().map(a=><tr key={a.id}><td><strong>{data.employees.find(e=>e.id===a.employeeId)?.name}</strong><small>{data.scenario.title}</small></td><td>{formatDate(a.startedAt)}</td><td>{a.mode}</td><td>{a.score==null?'Not recorded':a.score+'%'}</td><td><Badge status={a.result || a.state}/></td><td><button className="text-button" onClick={()=>openAttempt(a)}>Open attempt →</button></td></tr>)}</tbody></table></div> : <Empty title="No matching attempts">Adjust your filters or wait for game results to arrive.</Empty>}</section><section className="panel definitions"><h2>What these metrics mean</h2>{data.metricDefinitions.map(([term,definition])=><div key={term}><strong>{term}</strong><p>{definition}</p></div>)}</section></>;
}
function Sessions({ data, openAttempt }) {
  return <><div className="page-title"><div><span className="eyebrow">GAME ACTIVITY</span><h1>Session observation</h1><p>Recorded activity and connection state from the training build.</p></div><span className="date-chip">Last refreshed: {formatTime(data.updatedAt)}</span></div><div className="alert">Online: heartbeat within 60 seconds · Recent activity: within 5 minutes · Unknown: older activity. Presence does not prove that an employee is actively working.</div>{data.sessions.length ? data.sessions.slice().reverse().map(s=>{const seconds=(Date.parse(data.updatedAt)-Date.parse(s.lastActivity))/1000;const presence=s.state==='ended'?'ended':seconds<=60?'online':seconds<=300?'recent_activity':'unknown';const attempts=data.attempts.filter(a=>a.sessionId===s.id);return <section className="panel session-card" key={s.id}><div className="section-heading"><div><h2>{data.employees.find(e=>e.id===s.employeeId)?.name}</h2><p>{data.scenario.title} · {s.build}</p></div><Badge status={presence}/></div><p className="muted">Last received activity: {formatTime(s.lastActivity)} · Session started: {formatTime(s.startedAt)}</p>{presence==='unknown' && <div className="alert warning">Connection state is unknown. No recent heartbeat has been received.</div>}{attempts.map(a=><button className="result-row" key={a.id} onClick={()=>openAttempt(a)}><span><strong>{label(a.state)}</strong><small>{a.events.filter(e=>e.type==='answer').length} recorded answers · {a.mode}</small></span><span>Review timeline →</span></button>)}{!attempts.length && <p className="muted">No scenario has been started in this session.</p>}</section>;}) : <section className="panel"><Empty title="No game sessions received">Authorized game activity will appear after the training build signs in.</Empty></section>}</>;
}
function Resources({ data }) { return <><div className="page-title"><div><span className="eyebrow">WORKSHOP RESOURCES</span><h1>Installation & support</h1><p>Get ready for training with your existing Easy Express identity.</p></div></div><div className="dashboard-grid equal"><section className="panel"><Icon name="resources"/><h2>Your approved game build</h2><div className="alert warning">{data.demo ? 'Demonstration only. Sample results are fictional; no employee game access is granted.' : data.installerAvailable ? 'An approved training installer is available for authorized employees.' : 'The approved employee training installer has not been published yet. Contact your training administrator.'}</div>{data.installerAvailable && !data.demo && <DownloadInstaller/>}<ol className="resource-steps"><li>Get the approved training build from your administrator.</li><li>Extract it to a local folder and launch Easy Express.</li><li>Sign in with your provisioned game account.</li><li>Choose your assignment in the training session selector, then open the component tutorial or replay knowledge check.</li><li>Keep the game connected until the submission queue is empty, then review your results here.</li></ol></section><section className="panel"><h2>System requirements</h2><p>The source targets a Windows standalone Unity build. A tested minimum hardware specification has not been supplied.</p><dl className="details"><div><dt>Platform</dt><dd>Windows standalone (source target)</dd></div><div><dt>CPU / memory / GPU</dt><dd>Minimums not verified</dd></div><div><dt>Connection</dt><dd>Required for employee authorization and reporting</dd></div><div><dt>Game engine</dt><dd>Unity 6000.3.2f1</dd></div></dl><h3>When something goes wrong</h3><details><summary>My sign-in is denied</summary><p>Confirm your game email and password. Ask your administrator to check that your PlayFab ID has active employee access.</p></details><details><summary>My result hasn’t appeared</summary><p>Check the game’s reporting status. A pending event remains queued and retries after connection recovery. An unfinished check does not produce a finalized score.</p></details><details><summary>I reached the attempt limit</summary><p>Contact your administrator for another assignment. Free practice does not complete an assigned assessment.</p></details></section></div><section className="panel"><h2>Learning guide: component fundamentals</h2><div className="guide-grid">{[['Identify before replacing','Review the GPU, RAM, CPU cooler and PSU in the component tutorial.'],['Use the symptom to guide checks','Check power leads for no-power symptoms, storage detection for no-boot symptoms, and cooling connections for fan problems.'],['Handle components safely','Review CPU contact handling, tempered glass support and thermal paste procedures in the game’s lessons.']].map(([t,p])=><article key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></section></>; }
function DownloadInstaller() {
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  return <><button className="btn" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const d=await api('installer');window.location.assign(d.downloadUrl);}catch(e){setError(e.message);}finally{setBusy(false);}}}>{busy?'Preparing download…':'Download approved installer'}</button>{error && <div className="alert error" role="alert">{error}</div>}</>;
}
export default function TrainingPortal() {
  const [route,setRoute]=useState(window.location.hash.slice(2)||''),[data,setData]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState(null),[search,setSearch]=useState('');
  const navigate=p=>{window.location.hash='/'+p;setDialog(null);};
  useEffect(()=>{const f=()=>setRoute(window.location.hash.slice(2)||'');window.addEventListener('hashchange',f);return()=>window.removeEventListener('hashchange',f);},[]);
  useEffect(()=>{ let active=true;api('snapshot').then(d=>{if(active)setData(d);}).catch(e=>{if(active&&e.status!==401)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;}; },[]);
  const signedInId=data?.me.id;
  useEffect(()=>{if(!signedInId||route!=='sessions')return;const timer=window.setInterval(()=>{api('snapshot').then(setData).catch(e=>setError(e.message));},30000);return()=>window.clearInterval(timer);},[signedInId,route]);
  const refresh=async()=>{const d=await api('snapshot');setData(d);return d;};
  const run=async(action,input,success)=>{setBusy(true);setError('');setNotice('');try{await api(action,input);const d=await refresh();if(success)setNotice(success);return d;}catch(e){setError(e.message);}finally{setBusy(false);}};
  const login=async input=>{setBusy(true);setError('');try{setData(await api('login',input));navigate('dashboard');}catch(e){setError(e.message);}finally{setBusy(false);}};
  const demo=async()=>{setBusy(true);setError('');try{setData(await api('demo'));navigate('dashboard');}catch(e){setError(e.message);}finally{setBusy(false);}};
  if(loading)return <div className="loading"><Brand/><p role="status">Checking your workspace…</p></div>;
  if(!data)return route==='login'?<Login onSubmit={login} onBack={()=>navigate('')} busy={busy} error={error}/>:<PublicPage busy={busy} onLogin={()=>navigate('login')} onDemo={demo} error={error}/>;
  const admin=data.me.role!=='employee', page=route || 'dashboard';
  const tabs=admin?[['dashboard','Overview'],['employees','Employees'],['training','Training management'],['performance','Performance review'],['sessions','Session observation'],['resources','Resources & support']]:[['dashboard','Dashboard'],['training','My training'],['performance','My performance'],['resources','Resources & support']];
  const openAttempt=a=>setDialog({type:'attempt',id:a.id}),openAssignment=a=>setDialog({type:'assignment',id:a.id});
  const selectedAttempt=dialog?.type==='attempt'?data.attempts.find(a=>a.id===dialog.id):null;
  const selectedAssignment=dialog?.type==='assignment'?data.assignments.find(a=>a.id===dialog.id):null;
  const groups=[...new Set(data.employees.filter(e=>e.active).map(e=>e.group))];
  const employee=dialog?.type==='employee'?data.employees.find(e=>e.id===dialog.id):null;
  return <div className="workspace"><aside className="sidebar"><Brand/><div className="workspace-label">{data.me.role==='ceo'?'CEO WORKSPACE':admin?'ADMINISTRATOR':'EMPLOYEE WORKSPACE'}</div><nav aria-label="Workspace navigation">{tabs.map(([id,title])=><a href={'#/'+id} key={id} className={page===id?'active':''} aria-current={page===id?'page':undefined}><Icon name={id}/>{title}</a>)}</nav><div className="sidebar-bottom"><div className="secure-note"><Icon name="check"/><span>Authorized access<small>Connected to your game identity</small></span></div><button className="text-button" onClick={async()=>{await api('logout');setData(null);navigate('');}}>Sign out</button></div></aside><div className="workspace-body"><header className="workspace-header"><span>Training workspace <span className="breadcrumb">/ {tabs.find(([id])=>id===page)?.[1]||'Overview'}</span></span><div className="header-actions"><button className="text-button" disabled={busy} onClick={()=>run('snapshot',{},'Workspace refreshed')}>Refresh</button><div className="avatar">{initials(data.me.name)}</div><div><strong>{data.me.name}</strong><small>{data.me.role==='ceo'?'CEO · manages administrator access':admin?'Training administrator':'Employee'}</small></div></div></header>{data.demo && <div className="demo-banner"><span><strong>THESIS DEMONSTRATION</strong> Fictional employees & sample sessions · Isolated from production</span><label><span className="sr-only">Demonstration role</span><select value={data.me.role} disabled={busy} onChange={async e=>{setBusy(true);try{setData(await api('demoRole',{role:e.target.value}));navigate('dashboard');}catch(e){setError(e.message);}finally{setBusy(false);}}}><option value="ceo">View as CEO</option><option value="admin">View as administrator</option><option value="employee">View as employee</option></select></label></div>}<main className="workspace-content" id="main-content">{error && <div role="alert" className="alert error">{error}<button className="text-button" onClick={()=>setError('')}>Dismiss</button></div>}{notice && <div role="status" className="alert success">{notice}</div>}
      {page==='dashboard' && <Dashboard data={data} navigate={navigate} admin={admin} openAttempt={openAttempt} openAssignment={openAssignment}/>}
      {page==='training' && <><div className="page-title"><div><span className="eyebrow">A CLEAR PATH TO PRACTICE</span><h1>{admin?'Training management':'My training'}</h1><p>Assignments stay connected to the employee, game scenario and assessment rubric.</p></div>{admin && <button className="btn" onClick={()=>setDialog({type:'assign'})}>Assign training +</button>}</div><section className="panel scenario-panel"><div><Badge status="foundation"/><h2>{data.scenario.title}</h2><p>{data.scenario.purpose}</p><ul>{data.scenario.objectives.map(o=><li key={o}>{o}</li>)}</ul><p className="muted small">{data.scenario.criteria}</p></div><img src="/gallery/Diagnose.png" alt="Component tutorial in Easy Express"/></section><section className="panel"><h2>Assignments</h2><AssignmentTable data={data} admin={admin} onOpen={openAssignment}/></section>{admin && <section className="panel"><h2>Assessment settings</h2><p>Current pass mark: <strong>{data.rubric.passPercent}%</strong>. Changes apply to new assignments. Existing assignment and result rubrics remain unchanged.</p><form className="inline-form" onSubmit={e=>{e.preventDefault();run('rubric',{passPercent:Number(new FormData(e.currentTarget).get('passPercent'))},'New rubric saved. Existing assignments retain their original criteria.');}}><label>New pass mark<select name="passPercent" defaultValue={data.rubric.passPercent}>{[10,20,30,40,50,60,70,80,90,100].map(n=><option key={n} value={n}>{n}% · {n/10}/10 correct</option>)}</select></label><button className="btn secondary" disabled={busy}>Save new rubric</button></form><small className="muted">Current rubric version: {data.rubric.version}</small></section>}</>}
      {page==='employees' && admin && <><div className="page-title"><div><span className="eyebrow">PEOPLE & ACCESS</span><h1>Employee management</h1><p>Provision game identities, organize groups and manage training access.</p></div><button className="btn" onClick={()=>setDialog({type:'provision'})}>Provision employee +</button></div><section className="panel"><label className="search-field">Search employees<input placeholder="Name, group or PlayFab ID" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Department / group</th><th>Role</th><th>Account status</th><th>Actions</th></tr></thead><tbody>{data.employees.filter(e=>(e.name+' '+e.group+' '+e.id).toLowerCase().includes(search.toLowerCase())).map(e=><tr key={e.id}><td><button className="employee-link" onClick={()=>setDialog({type:'employee',id:e.id})}><span className="avatar">{initials(e.name)}</span><span><strong>{e.name}</strong><small>{e.id}</small></span></button></td><td>{e.group}</td><td>{e.id===data.me.id?label(data.me.role):label(e.role||'employee')}</td><td><Badge status={e.active?'active':'inactive'}/></td><td>{e.id!==data.me.id && <div className="table-actions"><button className="text-button" disabled={busy} onClick={()=>run('setActive',{id:e.id,active:!e.active},'Employee access updated.')}>{e.active?'Deactivate':'Reactivate'}</button>{data.me.role==='ceo' && e.active && <button className="text-button" disabled={busy} onClick={()=>setDialog({type:'role',id:e.id})}>{e.role==='admin'?'Revoke admin':'Grant admin'}</button>}</div>}</td></tr>)}</tbody></table></div></section>{data.me.role==='ceo' && <div className="alert">Only your CEO account can grant or revoke administrator access. Provision the existing game account first, then use Grant admin.</div>}</>}
      {page==='performance' && <Performance data={data} openAttempt={openAttempt}/>}{page==='sessions' && admin && <Sessions data={data} openAttempt={openAttempt}/>}{page==='resources' && <Resources data={data}/>}{!tabs.some(([id])=>id===page) && <Empty title="Page unavailable"><a href="#/dashboard">Return to your dashboard</a></Empty>}
      <footer className="workspace-footer"><span>Easy Express Training Portal</span><span>Last updated {formatTime(data.updatedAt)}</span></footer></main></div>
      {dialog && <Modal title={selectedAttempt?'Attempt review':selectedAssignment?'Assignment details':employee?employee.name:dialog.type==='provision'?'Provision employee':dialog.type==='role'?'Administrator access':'Assign training'} onClose={()=>setDialog(null)}>
      {error && <div className="alert error" role="alert">{error}</div>}
      {selectedAttempt && <AttemptReview attempt={selectedAttempt} data={data} busy={busy} onFeedback={t=>run('feedback',{attemptId:selectedAttempt.id,text:t},'Feedback saved for this attempt.')}/>}
      {selectedAssignment && <><Badge status={assignmentStatus(selectedAssignment,data.attempts)}/><h3>{selectedAssignment.title}</h3><p>{data.scenario.purpose}</p><ul>{data.scenario.objectives.map(o=><li key={o}>{o}</li>)}</ul><dl className="details"><div><dt>Due date</dt><dd>{formatDate(selectedAssignment.dueDate)}</dd></div><div><dt>Attempt limit</dt><dd>{selectedAssignment.attemptLimit}</dd></div><div><dt>Pass mark</dt><dd>{selectedAssignment.rubric.passPercent}% · {selectedAssignment.rubric.version}</dd></div></dl><div className="alert">Open the approved game build, select this assignment in the training session selector, then complete the component tutorial or knowledge replay. This portal does not launch the game automatically.</div><button className="btn" onClick={()=>navigate('resources')}>Installation & sign-in instructions <Icon name="arrow"/></button><h3>Attempts for this assignment</h3>{data.attempts.filter(a=>a.assignmentId===selectedAssignment.id).map(a=><button className="result-row" key={a.id} onClick={()=>openAttempt(a)}><span>{formatDate(a.startedAt)} · {label(a.result||a.state)}</span><span>Review →</span></button>)}</>}
      {employee && <><p>{employee.group} · {employee.email}</p><Badge status={employee.active?'active':'inactive'}/><form onSubmit={e=>{e.preventDefault();run('editEmployee',{id:employee.id,...Object.fromEntries(new FormData(e.currentTarget))},'Employee profile updated.');}}><div className="form-grid"><label>Employee name<input name="name" defaultValue={employee.name} required/></label><label>Department / group<input name="group" defaultValue={employee.group} required/></label></div><button className="btn secondary" disabled={busy}>Save employee profile</button></form><h3>Assignments</h3><AssignmentTable data={{...data,assignments:data.assignments.filter(a=>a.employeeId===employee.id)}} onOpen={openAssignment}/><h3>Attempt history & feedback</h3>{data.attempts.filter(a=>a.employeeId===employee.id).map(a=><button className="result-row" key={a.id} onClick={()=>openAttempt(a)}><span>{formatDate(a.startedAt)} · {label(a.result||a.state)}</span><span>{a.score==null?'—':a.score+'%'} →</span></button>)}</>}
      {dialog.type==='role' && <><p>{data.employees.find(e=>e.id===dialog.id)?.name} will {data.employees.find(e=>e.id===dialog.id)?.role==='admin'?'return to employee access':'receive administrator access to employee records, training assignments and performance reviews'}.</p><p className="muted">Only the CEO can make this change. The operation is recorded in the server audit history.</p><button className="btn" disabled={busy} onClick={async()=>{const d=await run('setRole',{id:dialog.id,role:data.employees.find(e=>e.id===dialog.id)?.role==='admin'?'employee':'admin'},'Administrator access updated.');if(d)setDialog(null);}}>Confirm role change</button></>}
      {dialog.type==='assign' && <form onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const d=await run('assign',f,'Training assignment saved.');if(d)setDialog(null);}}><p>Scenario: <strong>{data.scenario.title}</strong> · Current pass mark {data.rubric.passPercent}%</p><label>Assign to employee<select name="employeeId"><option value="">Select employee</option>{data.employees.filter(e=>e.active).map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label>Or assign to a whole group<select name="group"><option value="">Use individual employee</option>{groups.map(g=><option key={g}>{g}</option>)}</select></label><div className="form-grid"><label>Due date<input type="date" name="dueDate" required/></label><label>Attempt limit<input type="number" name="attemptLimit" min="1" max="20" defaultValue="3" required/></label></div><button className="btn" disabled={busy}>Save assignment</button></form>}
      {dialog.type==='provision' && <ProvisionForm data={data} groups={groups} busy={busy} onSave={async f=>{const d=await run('provision',f,'Employee access provisioned.');if(d)setDialog(null);}}/>}
      </Modal>}
    </div>;
}
